x<-read.table("household_power_consumption.txt",header=T,sep=";")
head(x)
dim(x)
x$Date <- as.Date(x$Date, format="%d/%m/%Y")
y <- x[(x$Date=="2007-02-01") | (x$Date=="2007-02-02"),]
y$Global_active_power <- as.numeric(as.character(y$Global_active_power))
y <- transform(y, timestamp=as.POSIXct(paste(Date, Time)), "%d/%m/%Y %H:%M:%S")
y$Sub_metering_1 <- as.numeric(as.character(y$Sub_metering_1))
y$Sub_metering_2 <- as.numeric(as.character(y$Sub_metering_2))
y$Sub_metering_3 <- as.numeric(as.character(y$Sub_metering_3))
y$Voltage <- as.numeric(as.character(y$Voltage))
y$Global_reactive_power <- as.numeric(as.character(y$Global_reactive_power))
par(mfrow=c(2,2))
plot(y$timestamp,y$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(y$timestamp,y$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(y$timestamp,y$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(y$timestamp,y$Sub_metering_2,col="red")
lines(y$timestamp,y$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
plot(y$timestamp,y$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()